code --install-extension bradlc.vscode-tailwindcss
code --install-extension catppuccin.catppuccin-vsc
code --install-extension chakrounanas.turbo-console-log
code --install-extension csstools.postcss
code --install-extension dbaeumer.vscode-eslint
code --install-extension eamodio.gitlens
code --install-extension esbenp.prettier-vscode
code --install-extension formulahendry.auto-rename-tag
code --install-extension mhutchie.git-graph
code --install-extension ms-azuretools.vscode-containers
code --install-extension ms-python.debugpy
code --install-extension ms-python.python
code --install-extension ms-python.vscode-pylance
code --install-extension ms-python.vscode-python-envs
code --install-extension ms-toolsai.jupyter
code --install-extension ms-toolsai.jupyter-keymap
code --install-extension ms-toolsai.jupyter-renderers
code --install-extension ms-toolsai.vscode-jupyter-cell-tags
code --install-extension ms-toolsai.vscode-jupyter-slideshow
code --install-extension ms-vscode-remote.remote-containers
code --install-extension naumovs.color-highlight
code --install-extension nomicfoundation.hardhat-solidity
code --install-extension oderwat.indent-rainbow
code --install-extension pkief.material-icon-theme
code --install-extension rangav.vscode-thunder-client
code --install-extension ritwickdey.liveserver
code --install-extension streetsidesoftware.code-spell-checker
code --install-extension vitaliymaz.vscode-svg-previewer
code --install-extension vscode-icons-team.vscode-icons
code --install-extension wix.vscode-import-cost